sudo: required
language: cpp
services:
  - docker
env:
  global:
    - secure: "ClJbOa4fZylQOvdsWmoNpmX2E5PrSzRVUtkt4E1J5S42qB+CiEZ5olZeCaWsr83scUBxFnr/Jq/fQoEQsdoe0jubnxfZUCP0/90HDJ0mwsGXU8QVaGre7o+XKhwREN3qacAurYsad4WWL9WC7K26yoTPislVuGQjBeYNYcsinlpEb3ILL3qyYA6XptSVFEW6yf12TCK3cjesH1YXzQJzJk+HhIKsBLn+va8eMrrgfgkwqbSC0N78LoNSPoBJEJz6Ao7/W0y1fhvFQWZ7qXlsrMfYoFvnXjhTGrOwWqKYjlNlKzITbPcyfSyskW2H3IZH4LugMgAiDJZesXguhsN1pZ5wI1XFbCxCHIQTVXDqu0h3WtGEPhpDD0dXnupWM2IgLwQRlKCpvBl4o8h89CPzurmk63D+UKjyrj5alRbMl41qR+1kDXe2AJOPe7llz8k9IWpj71zy/2YNMLTUR7g/3gKBnAgYymSrL2jl13PTKY2lm87og+TljTaZNbpBXRmSDVYakNgYRUZqfm4CECsUYcBo2DyGod+cKJf9BHYwqjlMBi3gKNCKXY4DC+4wxgqyrCSArfMNuoINswkXunWnsgJRWgO87rFUp+9nf9hifdmx8Go076V2bMNoCyBOtAFPgx/fAs2BTw6gFqSyrQ+eYmXFLcQJ7+ubP0KK540Vbgg=" # DOCKER_USER
    - secure: "G8MAUuk0a5LTLswLLvqO7tHg4ZMEry1/c9rO9km40oKXbm8AdmK9t2MM24o3amzoEnBzfictP583EuTgt2UW3Kg1YVcxRVFIeJCdQURlFguBfkjpT29yIMTCiIr25wL54ga7GAYUEXgR0Wd8OOl+9Swyr1HL3ul63Fz8+zWmG7YjK+Nze7EBG1wAq2Xr9ysZu1fOZrLMHHzT8wZ1cOBDOsyWxGxu/DSmNtNhCJzks6OgrxCS0tOyliNcktxYfL0JIUjlChAL+NQq9g/GUPAUIuoZYY8+5/jpuRf28Vppl04rzmETer4h/9vAvEtK8oCDI+VwszEek6IdjUiWQhApvJnwhMtRcVD0sI8XhR8zoxNEgndj6pUeErHu7rBCHlI0YK+yzOJjtXzojfGuuSAn/M4No3j5manjIMzqcxaLiOF3/PtxGCsKQRFuzPFdZiIOBO8EXuxdaz4Nflm7P4IsC+uqQQp7tnwJchJsDzfSGPV8u5yMfdSQuX+FEB5MJfgUoeC7dJmsIOFGSqlz8f0OhpqAc/ZfRw8+FqeBtRzZj/cFmk3s9LeMJMRQTAx0ADsJz2J8EcU32CQwlDpMh+RYKF5hKQcl+gTpIspOHJNj3AHP7gBd/m9a/bt+iJUbibup7slzfLjdn/uZfUZZ00AaWIu4utCJ0luKxy3YTdcHgVY=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/clang:latest
  - sudo docker run -itd --name build -v $(pwd)/upnp:/repo -v $(pwd)/build:/build spielhuus/clang:latest
  - sudo docker exec build git clone https://github.com/squawkcpp/upnp.git /repo
script:
  - sudo docker exec build cmake -H/repo -B/build -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DUPNP_TAG_VERSION=$TRAVIS_BRANCH
  - sudo docker exec build cmake --build /build
  - sudo docker exec build cmake --build /build --target test
  - sudo docker exec build cmake --build /build --target package

deploy:
  provider: releases
  api_key:
    secure: "C7cC2P68fhLP0PPbWyP1Ryc9CbQJ9FqbiDszLv/F2rHqkokTG7aBrKwTeFvS469mbFE4cDObjm9TJiU95TmgKj/IkNJPdquyqNPtl7hRuiGVxWlTowsDsk6ga5ke2yjbMP5NTHCuKOYInrkXH8AxqUMMdgj28M19nGwxIzBdIOri20aX2S2+i/zh5aHxEhuUiu0par5r8CY4TFvPyROxoOFNTr+J8Anet1rRNBKbD00EH/Q+pXVydS+AlG9lqAIBHSFHi5DEmZd5ra8s0eEx1BkoWL1GuDJGsxEpLjI+k+EQBRdDor+c+Z5nQoRTsHqWJ766wuDL8UlmZTAL2gjMETjbmNwK9ciEoIv438OaDhHP2ebAce3YgDjCvIll1G7vrJ0x6ikdZKo+x60siPlnnkwIx8vEu9IW0kLKy6juWVAbPi8Epf+w1IMCUeltRZTfsRT+CIqfhHxoGyByRO1qKdBpx0M26KHtNLzhFpr56tfOUX/1A+QuUOYO5WTUNw5ceUegI1zWdzxzBJSY/yFrSe3qSXD5acXCLE4CnHxDNtWcy01LQ5hoZ53//FWGG8EU5eRK9nVtzN9+vWXX+dBuBcu9+Os0mv8wziqgXzSlHohj3hodp3HnmmJWp9X3dQnNCncC+5pW3jR70pJbt66a9hYNfR91KV7hpA8+0Mk585w="
  file: '$(pwd)/build/upnp_$TRAVIS_BRANCH.tar.gz'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: squawkcpp/upnp

after_success:
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=squawk/upnp
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - sudo docker build -f docker/Dockerfile --build-arg UPNP_TAG_VERSION=$TRAVIS_BRANCH -t $REPO:$COMMIT .
  - sudo docker tag $REPO:$COMMIT $REPO:$TAG
  - sudo docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - sudo docker push $REPO

